version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:v2.0.1
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: dart test/app_test.dart
      - run: flutter build apk --release

