version: 2
jobs:
  build:
    docker:
      - image: cirrusci/flutter:latest
    steps:
      - checkout
      - run: flutter doctor
      - run: flutter pub get
      - run: flutter test test_driver/app.dart
      - run: flutter build apk --release

